### ISSUE TITLE
Gradle not working

### ISSUE THREAD

**Issue by SyedWasiHaider** [CodeFalling/RecyclerViewSwipeDismiss#3]
I just tried importing your library through gradle and got this...

Error:(29, 13) Failed to resolve: com.github.CodeFalling:RecyclerViewSwipeDismiss:v1.1.1
<a href="openFile">Show in File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

**Comment by xcodebuild** [comment]
It seems there is a  big problem with [`jitpack.io`](https://jitpack.io/).I will report this to it and upload my library to maven central.It may take some time.

**Comment by xcodebuild** [comment]
Now it works,you can try again.

**Comment by sohailhaider** [comment]
Same Issue again I can't get library on Gradle
